// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Stream struct {
	ID        int32          `json:"id"`
	Channel   string         `json:"channel"`
	Thumbnail string         `json:"thumbnail"`
	Streamer  sql.NullString `json:"streamer"`
}

type User struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}
